survos_base:
  theme: tabler
#  theme: start-bootstrap
#  menu:
#    enable: true
#    main_menu: survos_sidebar_menu
#    breadcrumb_menu: true
#

twig:
  globals:
    theme: tabler
  paths:
    'vendor/survos/base-bundle/src/Resources/views/tabler': 'theme'
